displayName=Better NPC Highlight Revamped
author=Oridjinn
support=
description=An EVEN MORE customizable NPC highlight, now with more presets.
tags=npc,tag,highlight,indicator,custom,overlay,respawn,hide,entity,id,name
plugins=com.betternpchighlightrevamped.BetterNpcHighlightPlugin